### ISSUE TITLE
on bar charts missing data causes last column to appear first

### ISSUE THREAD

**Issue by clairepowell** [Financial-Times/nightingale#27]
![image](https://cloud.githubusercontent.com/assets/12644597/7861715/b6215b2e-0549-11e5-9215-7430dd2c084c.png)

```
date	value
2005	4
2006	6
2007	8
2008	3
2009	-
2010	6
```

**Comment by kavanagh** [comment]
![nightingale_ft_com__test](https://cloud.githubusercontent.com/assets/684559/7886959/8462a55c-0625-11e5-866c-4e88ad9fcb76.png)

This example is just using the #test data.

**Comment by peter-mouland** [comment]
fixed with https://github.com/Financial-Times/nightingale/commit/527bb9aed269fce2593b120833ced56f65c46e11
