### ISSUE TITLE
Column chart doesn't draw well when all values are negative

### ISSUE THREAD

**Issue by clairepowell** [Financial-Times/nightingale#48]
Andrew Whiffin on stats desk tried to create a column chart in Nightingale with all negative data points - outcome didn't work.

![image](https://cloud.githubusercontent.com/assets/12644597/8060482/831a29f4-0ebd-11e5-833c-4d6139c89e5d.png)
![image 1](https://cloud.githubusercontent.com/assets/12644597/8060483/83575bf8-0ebd-11e5-9b7b-8e423c2ecddc.png)

**Comment by radiodario** [comment]
Can we have the data? a screenshot doesn't work.

**Comment by radiodario** [comment]
I think this is an o-charts issue
