### ISSUE TITLE
Labels on the chart are not drawing

### ISSUE THREAD

**Issue by clairepowell** [Financial-Times/nightingale#81]
Eric Platt in New York has reported that when he saves a chart in Nightingale it occasionally doesn't draw the labels correctly on the output png

![ft us consumer confidence july 2015 7-17-15](https://cloud.githubusercontent.com/assets/12644597/8801014/420d2c6e-2faf-11e5-8fb2-8baca5e8fc48.png)
![us_consumer_confidence_retreats_under_greece_and_china_weight-line_chart-largewebinline-600x394](https://cloud.githubusercontent.com/assets/12644597/8801015/432a3ae2-2faf-11e5-9474-2143f4764ee4.png)
![ft google market cap update 7-17-15](https://cloud.githubusercontent.com/assets/12644597/8801016/44633de6-2faf-11e5-8b16-8df762919328.png)
![google_market_cap_jumps_65bn_following_earnings-line_chart-largewebinline-600x394](https://cloud.githubusercontent.com/assets/12644597/8801017/45b1a03e-2faf-11e5-8a8b-0ec251efa881.png)

**Comment by peter-mouland** [comment]
this should be fixed in the latest version.  If you still have problems, please let us know
bbb5b63d2365c40400475665641147123b76b3d0
