### ISSUE TITLE
Intraday charts bug

### ISSUE THREAD

**Issue by clairepowell** [Financial-Times/nightingale#87]
here's some intraday chart data that is not working out in Nightingale. I've attached the data, along with charts produced with both the box for 'intraday' charts checked and unchecked

![chart with intrday chart box ticked](https://cloud.githubusercontent.com/assets/12644597/9276987/452ad4e8-429f-11e5-9757-a266ceba03f1.png)
![chart without intraday chart ticked](https://cloud.githubusercontent.com/assets/12644597/9276988/4642eaaa-429f-11e5-8ad7-73e3812e2322.png)

I have the data in an email but cannot attach the spreadsheet here so let me know when this is picked up and I can send it across

**Comment by peter-mouland** [comment]
hey @clairepowell are you able to drag and drop the data as a csv or copy and paste the data into here?

**Comment by clairepowell** [comment]
![image](https://cloud.githubusercontent.com/assets/12644597/9303851/e1ebcf08-44d9-11e5-927c-470a5d1fc41a.png)

**Comment by clairepowell** [comment]
Here is the link to the spreadsheet - have uploaded it to our programme area on google drive

https://docs.google.com/a/ft.com/spreadsheets/d/1wKZ5Px2hi3LtuPP2H5kWOdLrE5zvG66-0L9B37xF2Nk/edit?usp=sharing
