### ISSUE TITLE
Intra-day cannot handle weekends

### ISSUE THREAD

**Issue by FTgremlin** [Financial-Times/nightingale#89]
### Priority
Medium

### Steps to Reproduce
1, Provide a .csv file that has weekend dates
2, Use nightingale to display this with intra-day checked

### Expected Results
Chart displays with weekend gaps ignored

### Actual Results
Chart has gaps where weekend data should be ignored

### Notes
None

**Comment by peter-mouland** [comment]
fixed in https://github.com/Financial-Times/nightingale/commit/808db3e51d61e0abf1c7af02c4deb453beb3a079

**Comment by FTgremlin** [comment]
Tested
