### ISSUE TITLE
Sort timeseries column in date order if it's backwards

### ISSUE THREAD

**Issue by FTgremlin** [Financial-Times/nightingale#91]
### Priority
Low

### Steps to Reproduce
1, Provide a .csv file that lists timeseries backwards (eg. Q1 2015 to Q1 2007)

### Expected Results
Chart automatically should order the data correctly (eg. Q1 2007 to Q1 2015)

### Actual Results
Chart is not generated properly, and can throw errors

### Notes
None

**Comment by peter-mouland** [comment]
decided not to sort as we show what the user gives us. Instead we will highlight the reverse data as a potential problem they should fix
