### ISSUE TITLE
If discarding data with the right hand panel open, PNG and Standard buttons remain visible

### ISSUE THREAD

**Issue by FTgremlin** [Financial-Times/nightingale#92]
### Priority
Trivial

### Steps to Reproduce
1, Click `demo data`
2, Click one of the charts to open the right hand panel
3, Hit `discard data`

### Expected Results
n/a

### Actual Results
See screenshot: notice the PNG and Standard buttons are visible in the bottom right.
![screen shot 2015-08-26 at 12 01 32](https://cloud.githubusercontent.com/assets/12858421/9491956/366c3190-4beb-11e5-8086-0ca7aae96135.png)

### Notes
None

**Comment by FTgremlin** [comment]
This is fixed on the master branch, but I'll close it for good when it's live.

**Comment by radiodario** [comment]
master branch = live

**Comment by FTgremlin** [comment]
@radiodario are you sure? I'm seeing this bug still occurring on nightingale.ft.com but not when I download a build and run it on localhost.

**Comment by peter-mouland** [comment]
ah, flakey test failed which is why it didn't deploy. re-running now

**Comment by peter-mouland** [comment]
fixed now
